name: code-coverage

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Create virtual serial ports
        run: |
          sudo apt update && sudo apt install -y libudev-dev socat ser2net
          chmod +x tools/create_virtual_device.sh && tools/create_virtual_device.sh &

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '-- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml
