name: code-coverage

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Setup Cargo tools
        run: |
          cargo install cargo-quickinstall
          cargo quickinstall cargo-tarpaulin
          cargo quickinstall cross

      - name: Add virtual device
        run: |
          sudo apt install -y libudev-dev socat ser2net
          chmod +x tools/start_virtual_device.sh
          tools/start_virtual_device.sh

      - name: Run cargo test
        run: cargo test

      - name: Run cargo-tarpaulin
        run: cargo tarpaulin --out Html --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3

      - name: Build Linux
        run: |
          cross build --release --target x86_64-unknown-linux-gnu

      - name: Build Windows
        run: |
          cross build --release --target x86_64-pc-windows-gnu

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ci-artifact
          path: |
            tarpaulin-report.html
            target/x86_64-unknown-linux-gnu/release/ser2tcp-tester
            target/x86_64-pc-windows-gnu/release/ser2tcp-tester.exe
